#!/usr/bin/env python3

#
# Created by Claude (Anthropic) - 2025
#

import argparse
import json
import os
from functools import cmp_to_key

import mfobjc
import mflocales

#
# Constants
#

website_repo = './../mac-mouse-fix-website'

#
# Helpers
#

def get_all_xcstrings_files() -> list[str]:
    """Get all .xcstrings files from both mac-mouse-fix and mac-mouse-fix-website repos."""
    main_files = mflocales.find_xcstrings_files('.')
    website_files = mflocales.find_xcstrings_files(website_repo)
    all_files = main_files + website_files
    all_files = sorted(all_files)

    return all_files

def get_all_xcstrings_files_with_ids() -> list[tuple[str, str]]:
    """
    Get all .xcstrings files with short identifiers.
    Returns list of (fileid, path) tuples.
    """
    paths = get_all_xcstrings_files()

    # Count occurrences of each base name
    name_counts: dict[str, int] = {}
    for path in paths:
        name = os.path.splitext(os.path.basename(path))[0]
        name_counts[name] = name_counts.get(name, 0) + 1

    # Assign unique ids
    name_seen: dict[str, int] = {}
    result: list[tuple[str, str]] = []

    for path in paths:
        name = os.path.splitext(os.path.basename(path))[0]

        if name_counts[name] > 1:
            # Duplicate name - add suffix
            idx = name_seen.get(name, 0) + 1
            name_seen[name] = idx
            fileid = f"{name}_{idx}"
        else:
            fileid = name

        result.append((fileid, path))

    return result

#
# Commands
#

def cmd_list(_args):
    """List all .xcstrings files from both repos."""
    files = get_all_xcstrings_files_with_ids()

    if not files:
        print("No .xcstrings files found.")
        return

    max_id_len = max(len(fileid) for fileid, _ in files)

    print(f"Found {len(files)} .xcstrings file(s):\n")
    for fileid, path in files:
        print(f"  {fileid.ljust(max_id_len)}  ({path})")


def escape_cell(value: str) -> str:
    """Escape tabs and newlines in cell values for TSV output."""
    if value is None:
        return ""
    return value.replace("\t", "\\t").replace("\n", "\\n").replace("\r", "\\r")


def extract_note_from_comment(comment: str) -> str:
    """
    Removes unnecessary autogenerated old-style plist stuff from comments generated by Interface Builder.

    When an old-style plist is detected, removes everything, except for the value for the 'Note', which is the actually note left by the developer.
    
    Example input:
        Class = "NSMenuItem"; title = "Regular"; ObjectID = "17P-PJ-tV1"; Note = "Scrolling > Smoothness > Regular Option";

    We implemented the same thing in mf-xcloc-editor [Jan 3 2026]
    
    """

    dict = mfobjc.NSPropertyListSerialization_loads(comment)
    if not mfobjc.isclass(dict, 'NSDictionary'): return comment

    note = mfobjc.NSDictionary_stringForKey(dict, 'Note')
    if not note: return ""
    
    return note


def cmd_inspect(args):
    """Inspect all string units from all .xcstrings files."""
    
    def print_help_and_exit(err): # TODO: Consolidate this with the help string passed to add_argument maybe? 
        print(
            f"Invalid args passed to 'mfstrings inspect' command:"
            f"\n"
            f"\n{err}"
            f"\n"
            f"\nUsage: ./run mfstrings inspect --cols <columns> [--sortcol <column>] [--pretty]"
            f"\n"
            f"\nAvailable columns:"
            f"\n  - {'\n  - '.join(all_columns)}"
            f"\n"
            f"\nExample:"
            f"\n  ./run mfstrings inspect --cols fileid,key,comment,en,tr_state,tr --sortcol comment"
            f"\n"
            f"\nOutput is sorted by the first column unless --sortcol is specified."
            f"\n"
            f"\n--pretty tries to make the output more human-readable. Without --pretty, the output is a TSV (Tab separated values) table"
        )
        exit(1)
    
    files = get_all_xcstrings_files_with_ids()
    if not files:
        print_help_and_exit("No .xcstrings files found.")

    # Collect all locales across all files
    locales = []
    if 1:
        
        all_locales: set[str] = set()
        file_data: list[tuple[str, dict]] = []  # (fileid, xcstrings_content)

        for fileid, path in files:
            with open(path, 'r', encoding='utf-8') as f:
                content = json.load(f)
                file_data.append((fileid, content))

                # Collect locales from this file
                for key, string_info in content.get('strings', {}).items():
                    localizations = string_info.get('localizations', {})
                    all_locales.update(localizations.keys())

        # Sort locales (en first, then alphabetically)
        locales = sorted(all_locales, key=lambda l: (l != 'en', l))

    # Build all available columns
    # Format: fileid, key, comment, en, <locale>_state, <locale>, ...
    columns = []
    if 1:
        all_columns = ['fileid', 'key', 'comment', 'en']
        for locale in locales:
            if locale == 'en':
                continue
            all_columns.append(f'{locale}_state')
            all_columns.append(locale)

        # Determine which columns to show
        if not args.cols:
            print_help_and_exit("Missing --cols arg")

        columns = args.cols.split(',')
        
        # Validate columns
        for col in columns:
            if col not in all_columns:
                print_help_and_exit(f"Unknown column: {col}")

    # Build all rows first (so we can sort)
    rows: list[list[str]] = []

    for fileid, content in file_data:
        strings = content.get('strings', {})

        for key in strings.keys():
            string_info = strings[key]
            comment = extract_note_from_comment(string_info.get('comment', ''))
            localizations = string_info.get('localizations', {})

            # Build a dict of all column values for this row
            row_data: dict[str, str] = {}
            if 1:
                row_data = {
                    'fileid': fileid,
                    'key': key,
                    'comment': comment,
                    'en': localizations.get('en', {}).get('stringUnit', {}).get('value', ''),
                }

                for locale in locales:
                    if locale == 'en':
                        continue
                    loc_data = localizations.get(locale, {})
                    string_unit = loc_data.get('stringUnit', {})
                    row_data[f'{locale}_state'] = string_unit.get('state', '')
                    row_data[locale] = string_unit.get('value', '')

            # Extract only requested columns in order
            row = [escape_cell(row_data.get(col, '')) for col in columns]
            rows.append(row)

    # Parse --sortcol
    sortcoli = -1
    if args.sortcol:
        if not args.sortcol in columns:
            print_help_and_exit(f"Column '{args.sortcol}' which was passed to --sortcol, was not found in columns passed to --col: {columns}")
        sortcoli = columns.index(args.sortcol)
                      
    # Sort
    args.sortcol
    def mfcmp(a, b):
        assert len(a) == len(b)

        if args.sortcol: # Sort by --sortcol
            if (x := mfobjc.NSString_localizedStandardCompare(a[sortcoli], b[sortcoli])): return x

        n = len(a)
        for i in range(n): # Sort by first, second, ... column
            if (x := mfobjc.NSString_localizedStandardCompare(a[i], b[i])): return x
        return 0;
    rows.sort(key=cmp_to_key(mfcmp))

    # Print header
    if args.pretty:
        print('\t|\t'.join(columns))
    else:
        print('\t'.join(columns))

    # Print rows
    for row in rows:
        if args.pretty:
            print('\t|\t'.join(row))
        else:
            print('\t'.join(row))


def main():

    # Validate cwd
    #   (Similar validation in uploadstrings.py > main())
    repo_name = os.path.basename(os.getcwd())
    assert repo_name == 'mac-mouse-fix', 'This script should be run from the mac-mouse-fix repo'
    assert os.path.isdir(website_repo), f'The mac-mouse-fix-website repo should be at {website_repo}'

    parser = argparse.ArgumentParser(
        description='Tool for inspecting and editing .xcstrings localization files.',
    )
    subparsers = parser.add_subparsers(dest='command', help='Available commands')

    # list command
    list_parser = subparsers.add_parser('list-files', help='List all .xcstrings files')
    list_parser.set_defaults(func=cmd_list)

    # inspect command
    inspect_parser = subparsers.add_parser('inspect', help='Inspect all string units (TSV output)') # - [ ] TODO: Consider adding a file-filter if this slows down the Claude's (currently takes 450ms) [Jan 2025]
    inspect_parser.add_argument('--pretty', action='store_true', help='Human-readable output with | separators')
    inspect_parser.add_argument('--cols', type=str, help='Comma-separated list of columns to show, in order (e.g., "tr_state,fileid,key,en,tr"). Omit this arg to see available columns. Output is sorted by first column unless --sortcol is specified.')
    inspect_parser.add_argument('--sortcol', type=str, help='Column to sort the table by. This column must also be passed to --cols.')
    inspect_parser.set_defaults(func=cmd_inspect)

    # Parse and execute
    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        return

    args.func(args)


if __name__ == '__main__':
    main()
